tools/cephfs_mirror: fix lock declaratie/locking
Clang complains:
```
/home/jenkins/workspace/ceph-master-compile/src/tools/cephfs_mirror/ClusterWatcher.cc:175:19: error: cannot use parentheses when declaring variable with deduced class template specialization type
  std::scoped_lock(m_lock);
                  ^
```
Resolves: rhbz#2002140

fixes: https://github.com/ceph/ceph/pull/42751
Signed-off-by: Willem Jan Withagen <wjw@digiware.nl>
(cherry picked from commit 3f952b9c9b69a361441952b279a39b164881ce12)