mgr/volumes: reverse params passed to `isinstace()`
fixes mypy error:

volumes/fs/operations/clone_index.py: note: In member "track" of class "CloneIndex":
volumes/fs/operations/clone_index.py:38: error: Argument 2 to "isinstance" has incompatible type "Union[VolumeException, Any]"; expected "Union[type, Tuple[Union[type, Tuple[Any, ...]], ...]]"

Fixes: https://tracker.ceph.com/issues/44393
Signed-off-by: Michael Fritch <mfritch@suse.com>
(cherry picked from commit 896448324f35bb1c307baff46e67a05d5d23e83b)
(cherry picked from commit ca653f44cf8a11991649143ae65d9131872b99f2)

Resolves: rhbz#1767144