cephadm: change base units lock to lock around all systemd file updates
The write_new call after we install the base units is also
a shared resource and not putting a lock around it can
result in failures there

```
cephadm/cephadmlib/systemd_unit.py", line 236, in update_files
    f.write(unit)
  File "/usr/lib64/python3.9/contextlib.py", line 126, in __exit__
    next(self.gen)
  File "/var/lib/ceph/bae6f1a8-41d1-11f0-90ec-fa163e5ca9b8/cephadm/cephadmlib/file_utils.py", line 52, in write_new
    os.rename(tempname, destination)
FileNotFoundError: [Errno 2] No such file or directory: '/etc/systemd/system/ceph-bae6f1a8-41d1-11f0-90ec-fa163e5ca9b8@.service.new' -> '/etc/systemd/system/ceph-bae6f1a8-41d1-11f0-90ec-fa163e5ca9b8@.service'
```

Signed-off-by: Adam King <adking@redhat.com>
(cherry picked from commit 52ff866689d103bdfad5ed12311a79efcd5ebd08)

Resolves: rhbz#2370450