cephadm: remove print statement about using vendored dataclasses
This was causing

2025-04-16T04:49:46.498723+0000 mgr.ceph-vpap-tfa-pc9eyk-node1-installer.dmeiut [ERR] host ceph-vpap-tfa-pc9eyk-node2 `cephadm ls` failed: Cannot decode JSON: using vendor
[]
Traceback (most recent call last):
  File "/usr/share/ceph/mgr/cephadm/serve.py", line 1617, in _run_cephadm_json
    return json.loads(''.join(out))
  File "/lib64/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/lib64/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/lib64/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

as the "using vendor" was added as part of the stdout which stopped caused it to
no longer be a valid json string

Signed-off-by: Adam King <adking@redhat.com>

Resolves: rhbz#2351292