rgw/cksum: GetObject omits checksum headers for Range requests
if we send response headers containing full-object checksums, clients
will compare them with the returned data and fail with:

> botocore.exceptions.FlexibleChecksumError: Expected checksum 4AAr8A== did not match calculated checksum: WbxXZw==

the only thing aws docs[1] say about Range requests refers to multipart
uploads:

> For completed uploads, you can get an individual part's checksum by using the GetObject or HeadObject operations and specifying a part number or byte range that aligns with a single part.

Fixes: https://tracker.ceph.com/issues/69936
Resolves: rhbz#2349928

[1] https://docs.aws.amazon.com/AmazonS3/latest/userguide/checking-object-integrity.html#Part-level-checksums

Signed-off-by: Casey Bodley <cbodley@redhat.com>
(cherry picked from commit 53098baf693353f65e19c8958ca2408b82b2b7a3)
(cherry picked from commit b7728936e77dcc00bf5bb871f2b447c9d95b1a44)