mgr/volumes: `threading.Event.isSet` no longer exists in py3
fixes mypy errors:

volumes/fs/async_job.py: note: In member "should_cancel" of class "JobThread":
volumes/fs/async_job.py:70: error: "Event" has no attribute "isSet"

volumes/fs/volume.py: note: In member "is_stopping" of class "VolumeClient":
volumes/fs/volume.py:59: error: "Event" has no attribute "isSet"

volumes/fs/volume.py: note: In member "list_fs_volumes" of class "VolumeClient":
volumes/fs/volume.py:106: error: "Event" has no attribute "isSet"

Fixes: https://tracker.ceph.com/issues/44393
Signed-off-by: Michael Fritch <mfritch@suse.com>
(cherry picked from commit aaed49a142722089f8a24ceb8b846b7c1c51d5f6)
(cherry picked from commit 157a028a81f2387b265dd81c2b7672504cb1bc17)

Resolves: rhbz#1767144