Revert "src/ceph-crash.in: remove unused frame in handler()"
This reverts commit 432c766a99f70884049bf7a1f268287a5a809777.

unused but required:

```
Traceback (most recent call last):
File "/usr/bin/ceph-crash", line 102, in <module>
main()
File "/usr/bin/ceph-crash", line 98, in main
time.sleep(args.delay * 60)
TypeError: handler() takes exactly 1 argument (2 given)
```

Fixes: https://tracker.ceph.com/issues/54422

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>
(cherry picked from commit 02e8e7d6e6d31b4735115f7820e015fc54997d9f)
(cherry picked from commit e6f1f52409c52c3fd9434015a04065c89d762a21)

Resolves: rhbz#2136912