tools/DataScan: Fix operator<< overloading for C++11
This is required to fix the following build failure caused by
the commit 6757b1ec8d969b8e9019f726890b7041f1a47795

This is required to fix the following build failure caused by
the commit 6757b1ec8d969b8e9019f726890b7041f1a47795

...
/builddir/build/BUILD/ceph-17.2.6/src/tools/cephfs/DataScan.cc:1146:32: \
error: no match for 'operator<<' (operand types are 'std::basic_ostream<char>' \
and 'DataScan::scan_links()::link_info_t')
 1146 |       dout(10) << " primary: " << q << dendl;
...

The required dependant upstream commit 92df0fcc649345f438d0d7cc6fab658c02060f07
to fix the build error uses the 'concept' which is only available in C++20.
The 6.1 build uses C++11. So this patch worksaround it by defining the
'struct linkinfo_t' outside the 'DataScan::scan_links' to make operator<<
overload work.

Signed-off-by: Kotresh HR <khiremat@redhat.com>

Resolves: rhbz#2343973