mgr/volumes: add missing `mgr` param
fixes mypy errors:

volumes/fs/operations/volume.py: note: In function "create_volume":
volumes/fs/operations/volume.py:216: error: Too few arguments for "remove_pool"
volumes/fs/operations/volume.py:223: error: Too few arguments for "remove_pool"
volumes/fs/operations/volume.py:224: error: Too few arguments for "remove_pool"

Fixes: https://tracker.ceph.com/issues/44393
Signed-off-by: Michael Fritch <mfritch@suse.com>
(cherry picked from commit a3b61a357730e0834ded4e6c47be0998bc4ea472)
(cherry picked from commit 7be1e6d155bb77fbe92939c08a3a35dfd7da10d2)

Resolves: rhbz#1767144