mgr/volumes: assert JobThread class
fixes mypy error:

volumes/fs/async_job.py: note: In member "run" of class "JobThread":
volumes/fs/async_job.py:43: error: "Thread" has no attribute "should_cancel"

Fixes: https://tracker.ceph.com/issues/44393
Signed-off-by: Michael Fritch <mfritch@suse.com>
(cherry picked from commit 6907c440e1350e4088c0562bffcc08439633298f)
(cherry picked from commit 3375318d3b56e0f8bd30a21f0b1d9acac17cf4ce)

Resolves: rhbz#1767144