mgr/volumes: import VolumeException
fixes mypy errors:

volumes/fs/operations/index.py: note: In member "track" of class "Index":
volumes/fs/operations/index.py:19: error: Name 'VolumeException' is not defined

volumes/fs/operations/index.py: note: In member "untrack" of class "Index":
volumes/fs/operations/index.py:22: error: Name 'VolumeException' is not defined

Fixes: https://tracker.ceph.com/issues/44393
Signed-off-by: Michael Fritch <mfritch@suse.com>
(cherry picked from commit 5b9d5e2e43e3d2e2d391e9bce2328868a6159e53)
(cherry picked from commit c207b35fdcc19a8cc455e2de0b8ac50337a2e0a8)

Resolves: rhbz#1767144