rgw/multisite: add type to RGW_OP_SYNC_DATALOG_NOTIFY2
without that the following errors are happening during sync:

ERROR: AWS4 completion for operation: 0, NOT IMPLEMENTED
op->ERRORHANDLER: err_no=-2201 new_err_no=-2201

Signed-off-by: Yuval Lifshitz <ylifshit@redhat.com>
(cherry picked from commit 98e72261ea7bbfe6c3642e795758fc9cf751221e)

Conflicts:
	src/rgw/rgw_op_type.h
	src/rgw/rgw_rest_s3.cc
 - Upstream SAL

Resolves: rhbz#2075214
Signed-off-by: Adam C. Emerson <aemerson@redhat.com>