mgr/volumes: fix positional str formatting
fixes mypy error:

volumes/fs/operations/group.py: note: In function "create_group":
volumes/fs/operations/group.py:135: error: Not all arguments converted during string formatting

Fixes: https://tracker.ceph.com/issues/44393
Signed-off-by: Michael Fritch <mfritch@suse.com>
(cherry picked from commit f46b5059e635228f07dd5fe593f2d7454c3aa67b)
(cherry picked from commit 21f9cebf93b624c556ab117972a5bbacc8aa4737)

Resolves: rhbz#1767144